/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChangeLocal: typeof import('./src/components/set/preference/ChangeLocal.vue')['default']
    CnblogsTest: typeof import('./src/components/test/CnblogsTest.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    GeneralSetting: typeof import('./src/components/set/GeneralSetting.vue')['default']
    HexoTest: typeof import('./src/components/test/HexoTest.vue')['default']
    HugoTest: typeof import('./src/components/test/HugoTest.vue')['default']
    KmsTest: typeof import('./src/components/test/kmsTest.vue')['default']
    PlatformSetting: typeof import('./src/components/set/PlatformSetting.vue')['default']
    PublishIndex: typeof import('./src/components/publish/PublishIndex.vue')['default']
    PublishSetting: typeof import('./src/components/set/PublishSetting.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetIndex: typeof import('./src/components/set/SetIndex.vue')['default']
    SiyuanTest: typeof import('./src/components/test/SiyuanTest.vue')['default']
    TypechoTest: typeof import('./src/components/test/TypechoTest.vue')['default']
    VitepressTest: typeof import('./src/components/test/VitepressTest.vue')['default']
    WordpressTest: typeof import('./src/components/test/WordpressTest.vue')['default']
    YuqueTest: typeof import('./src/components/test/YuqueTest.vue')['default']
  }
}
